language: go

go:
#  - tip
  - 1.7
#  - 1.6
#  - 1.5
#  - 1.4
#  - 1.3
#  - 1.2
#  - 1.1

before_install:
  - curl --silent -O http://apache.claz.org/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz
  - tar -zxvf zookeeper*tar.gz
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go test ./...

notifications:
  email:
    on_success: change
    on_failure: always
